name: recetas_aplazo
description: "Buscador de recetas"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  dio: ^5.9.0
  go_router: ^16.2.2
  pipen: ^2.2.3
  pipen_bloc: ^1.2.4
  flutter_formux: ^1.0.7
  async: ^2.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/img/