name: recetas_aplazo
description: "Buscador de recetas"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  dio: ^5.9.0
  go_router: ^16.2.2
  pipen: ^2.2.3
  pipen_bloc: ^1.2.5
  flutter_formux: ^1.0.7
  async: ^2.13.0
  path_provider: any
  path: any
  objectbox: ^4.3.1
  objectbox_flutter_libs: any
  dio_cache_interceptor: ^4.0.3
  http_cache_objectbox_store: ^2.0.0
  get_it: ^8.2.0
  like_button: ^2.1.0
  equatable: ^2.0.7
  cached_network_image: ^3.4.1
  bloc: ^9.0.0
  mocktail: ^1.0.4
  bloc_test: ^10.0.0

dev_dependencies:
  build_runner: any
  objectbox_generator: any
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/img/